order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>/', views.Payment.as_view(), name='pay'),
    path('save-order/', views.SaveOrder.as_view(), name='save_order'),
    path('list-order/', views.ListOrder.as_view(), name='list_order'),
    path('order-detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.CreatePerfil.as_view(), name='create'),
    path('update/', views.UpdatePerfil.as_view(), name='update'),
    path('login/', views.LoginPerfil.as_view(), name='login'),
    path('logout/', views.LogoutPerfil.as_view(), name='logout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.ListProduct.as_view(), name='list_products'),
    path('add-to-cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('remove-to-cart/', views.RemoveToCart.as_view(), name='remove_to_cart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('purchase-summary/', views.PurchaseSummary.as_view(), name='purchase_summary'),
    path('search/', views.SearchProduct.as_view(), name='search_product'),
    path('<str:slug>/', views.ProductDetail.as_view(), name='details'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
"""
Pedido:
        user - FK User
        total - Float
        status - Choices
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),

        ItemPedido:
            pedido - FK pedido
            produto - Char
            produto_id - Int
            variacao - Char
            variacao_id - Int
            preco - Float
            preco_promocional - Float
            quantidade - Int
            imagem - Char
"""
STATUS_CHOICES = (
    ('A', 'Aprovado'), ('P', 'Pendente'), ('C', 'Criado'), 
    ('R', 'Recusado'), ('E', 'Enviado'), ('F', 'Finalizado'),
)


class Pedido(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING, verbose_name='Usuário')
    total = models.FloatField()
    total_quantity = models.PositiveIntegerField()
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='C')
    
    def __str__(self):
        return f'Pedido Nº {self.pk}'


class ItemPedido(models.Model):
    order = models.ForeignKey(Pedido, models.CASCADE, verbose_name='Pedido')
    product = models.CharField('Produto', max_length=255)
    product_id = models.PositiveIntegerField('ID do produto')
    variation = models.CharField('Variação', max_length=100)
    variation_id = models.PositiveIntegerField('ID da variação')
    price = models.FloatField(verbose_name='Preço')
    promotional_price = models.FloatField('Preço promocional')
    quantity = models.PositiveIntegerField('Quantidade')
    image = models.CharField(max_length=2000, verbose_name='Imagem')

    def __str__(self):
        return f'Item do {self.order}'.capitalize()
    
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

product/models.py
from django.db import models
from PIL import Image
from django.utils.text import slugify
from utils import functions

CHOICES = ('V', 'Variável'), ('S', 'Simples')
IMG_DEFAULT_SIZE = (400, 250)


class Produto(models.Model):
    name = models.CharField('Nome', max_length=255)
    short_description = models.TextField(
        'Descrição curta', blank=True, null=True, max_length=200
    )
    long_description = models.TextField('Descrição longa', blank=True, null=True)
    image = models.ImageField('Imagem do produto', upload_to='products/img/%Y/%b/')
    slug = models.SlugField('Slug', unique=True, blank=True, null=True)
    marketing_price = models.FloatField('Preço marketing')
    promotional_marketing_price = models.FloatField(
        'Preço marketing promocional', default=0
    )
    variation_type = models.CharField(
        'Tipo', max_length=1, choices=CHOICES, default='V'
    )
    
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            try:
                pk = Produto.objects.all().order_by('-id').first().id + 1
            except:
                pk = 1
            self.slug = f'{slugify(self.name)}-{pk}'
            
        super().save(*args, **kwargs)
        self.resize_image()

    def resize_image(self):        
        img = Image.open(self.image.path)
        x, y = img.size
        if x <= IMG_DEFAULT_SIZE[0] and y <= IMG_DEFAULT_SIZE[1]:
            img.close()
            return
        
        new_img = img.resize(IMG_DEFAULT_SIZE, Image.ANTIALIAS)
        new_img.save(self.image.path, quality=70, optimize=True)
        img.close()
        new_img.close()
    
    def get_marketing_price_formatted(self):
        return functions.format_money_value(self.marketing_price)
    get_marketing_price_formatted.short_description = 'Preço'
    
    def get_promotional_price_formatted(self):
        return functions.format_money_value(self.promotional_marketing_price)
    get_promotional_price_formatted.short_description = 'Preço promocional'

 
class Variacao(models.Model):
    product = models.ForeignKey(Produto, models.CASCADE, verbose_name='Produto')
    name = models.CharField(
        'Nome', max_length=255, default=product.name
    )
    price = models.FloatField('Preço')
    promotional_price = models.FloatField('Preço promocional', default=0)
    stock = models.PositiveIntegerField('Estoque', default=1)
    
    def __str__(self):
        return self.name or self.product.name
    
    
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'
        

product/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from perfil.models import Perfil
from django.contrib import messages
from .models import Produto, Variacao
from django.db.models import Q


class ListProduct(ListView):
    model = Produto
    template_name = 'list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']


class ProductDetail(DetailView):
    model = Produto
    template_name = 'details.html'
    context_object_name = 'product_detail'
    slug_url_kwarg = 'slug'

class AddToCart(View):
    def get(self, *args, **kwargs):            
        http_referer = self.request.META.get('HTTP_REFERER', reverse('product:list_products'))
        variation_id = self.request.GET.get('vid')
        if not variation_id:
            messages.error(self.request, 'Error')
            return redirect(http_referer)
        
        variation = get_object_or_404(Variacao, id=variation_id)
        product = variation.product
        unit_price = variation.price
        promotional_unit_price = variation.promotional_price
        
        if variation.stock < 1:
            messages.error(self.request, 'Estoque insuficiente.')
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()
            
        was_add = True
        carrinho = self.request.session['carrinho']            
        if variation_id in carrinho:
            stock = variation.stock
            cart_quantity = carrinho[variation_id]['quantity']
            cart_quantity += 1
            if stock < cart_quantity:
                messages.warning(self.request, 'Estoque insuficiente.')
                cart_quantity = variation.stock
                was_add = False
                
            carrinho[variation_id]['quantity'] = cart_quantity
            carrinho[variation_id]['quantitative_price'] = cart_quantity * unit_price
            carrinho[variation_id]['promotional_quantitative_price'] = cart_quantity * promotional_unit_price
            
        
        else:
            carrinho[variation_id] = dict(
                product_id = product.id,
                product_name = product.name,
                variation_name = variation.name,
                variation_id = variation.id,
                unit_price = unit_price,
                promotional_unit_price = promotional_unit_price,
                quantity = 1,
                slug = product.slug,
                image = product.image.name if product.image else '',
                
            )
            quantity = carrinho[variation_id]['quantity']
            carrinho[variation_id]['quantitative_price'] = quantity * unit_price
            carrinho[variation_id]['promotional_quantitative_price'] = quantity * promotional_unit_price
        
        self.request.session.save()
        if was_add:
            messages.success(self.request, f'{product.name} adicionado ao carrinho.')
        return redirect(http_referer)


class RemoveToCart(View):
    def get(self, request, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER', reverse('product:list_products'))
        variation_id = self.request.GET.get('vid')
        carrinho = self.request.session.get('carrinho')
        if not variation_id:
            return redirect(http_referer)
        
        if not variation_id or not carrinho or variation_id not in carrinho:        
            return redirect(http_referer)

        product_name = carrinho[variation_id]['product_name']
        variation_name = carrinho[variation_id]['variation_name']
        messages.warning(
            self.request, 
            f'{product_name} {variation_name} removido.'
        )
        del self.request.session['carrinho'][variation_id]
        self.request.session.save()
        return redirect(http_referer)


class Cart(View):
    def get(self, request, *args, **kwargs):
        return render(self.request, 'cart.html')


class PurchaseSummary(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:create')
        
        perfil = Perfil.objects.filter(user=self.request.user).exists()
        if not perfil:
            messages.error(self.request, 'Usuário não tem perfil.')
            return redirect('perfil:create')
        
        if not self.request.session.get('carrinho', {}):
            messages.error(self.request, 'Carrinho vazio.')
            return redirect('product:list_products')
        
        context = {
            'user': self.request.user,
            'cart': self.request.session.get('carrinho', {})
        }
        return render(self.request, 'salesummary.html', context)


class SearchProduct(ListProduct):
    def get_queryset(self, *args, **kwargs):
        search_field = self.request.GET.get('search_field') or self.request.session.get('search_fiedl')
        qs = super().get_queryset(*args, **kwargs)
        if not search_field: return qs
        
        self.request.session['search_fiedl'] = search_field
        
        qs = qs.filter(
            Q(name__icontains=search_field)|
            Q(short_description__icontains=search_field)|
            Q(long_description__icontains=search_field)
        )
        
        self.request.session.save()
        return qs
    

templates/partials/_cart.html
{% load static %}
{% load myfilters %}
<div class="table-responsive">
    <table class="table">
        <tr>
            <th class="d-none d-lg-block">Imagem</th>
            <th>Produto</th>
            <th>V.</th>
            <th>QTD.</th>
            <th>Total</th>
        </tr>

        {% for item in request.session.carrinho.values %}
        <tr>
            <td class="d-none d-lg-block">
                <a href="{% url 'product:details' item.slug %}">
                    <img class="cart-img" src="{% get_media_prefix %}{{item.image}}">
                </a>
            </td>
            <td>
                {{item.product_name}}
                <a class="ml-3" href="{% url 'product:remove_to_cart' %}?vid={{item.variation_id }}">
                    <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                </a>
            </td>
            <td>{{item.variation_name}}</td>
            <td>
                {{item.quantity}} x
                {% if item.promotional_unit_price %}
                    {{item.promotional_unit_price|format_money}}
                {% else %}
                    {{item.unit_price|format_money}}
                {% endif %}
            
            </td>
            {% if item.promotional_quantitative_price %}
                <td>R$ {{item.promotional_quantitative_price|format_money}}</td>
            {% else %}
                <td>R$ {{item.quantitative_price|format_money}}</td>
            {% endif %}
        </tr>
        {% endfor %}

    </table>
</div>

templates/partials/_footer.html
<footer class="container-fluid bg-primary">
    <div class="container text-light">
        <div class="row">
            <div class="col">
                <div class="p-1">
                    <span class="align-middle p-1">Feito com Django</span>
                </div>
            </div>
            <div class="col">
                <div class="p-1 text-right">
                    <span class="align-middle p-1">Por Luiz Otávio</span>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/partials/_head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'assets/custom/css/style.css' %}">

templates/partials/_messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert {{ message.tags }}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/partials/_nav.html
{% load myfilters %}
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'product:list_products' %}">E-commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">

            <li class="nav-item active">
                <a class="nav-link" href="{% url 'product:list_products' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
            </li>

            {% if request.user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Conta
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'order:list_order' %}">Meus pedidos</a>
                    <a class="dropdown-item" href="{% url 'perfil:create' %}">Atualizar dados</a>
                    <a class="dropdown-item" href="{% url 'perfil:logout' %}">Sair</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:create' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'perfil:create' %}">Criar conta</a>
            </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-link disabled" href="#">Disabled</a>
            </li>
            <li class="nav-item">
                <a class="nav-link nav-cart-link active" href="{% url 'product:cart' %}">
                    <span class="nav-cart-text mr-1">
                        Carrinho
                    </span>
                    {% if request.session.carrinho %}
                    <span class="nav-cart-count mr-1">
                        <strong>{{request.session.carrinho|get_cart_quantity}}x</strong>
                    </span>
                    {% endif %}
                    <span class="nav-cart-icon mr-2">
                        <i class="fas fa-shopping-cart"></i>
                    </span>
                </a>
            </li>

        </ul>
        <form class="form-inline my-2 my-lg-0" 
        action="{% url 'product:search_product' %}" method="get">
        {% csrf_token %}
            <input class="form-control mr-sm-2" 
            type="search" placeholder="Buscar produto"
             aria-label="Search" name="search_field" value="{{request.GET.search_field}}">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Buscar</button>
        </form>
    </div>
</nav>

templates/partials/_pagination.html
{% if is_paginated %}
<div class="col mt-3 mb-3">
    <div class="row">
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}


                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}

templates/partials/_products.html
{% load static %}
{% load myfilters %}

<div class="row">
    <div class="col">
        <h3>Pedido N. {{pedido.pk}}</h3>

        <div class="row mt-4">
            <div class="col-lg-2 font-weight-bold">Número do pedido:</div>
            <div class="col-lg-4">{{pedido.id}}</div>
            <div class="col-lg-2 font-weight-bold">Total a pagar:</div>
            <div class="col-lg-4">{{pedido.total|format_money}}</div>

            <div class="col-lg-2 font-weight-bold">QTD. Itens:</div>
            <div class="col-lg-4">{{pedido.total_quantity}}</div>
            <div class="col-lg-2 font-weight-bold">Status:</div>
            <div class="col-lg-4">{{pedido.get_status_display}}</div>
        </div>

        <div class="row mt-4">
            <div class="col">
                <h3>Produtos</h3>
            </div>
        </div>

        <div class="table-responsive mt-3">
            <table class="table">
                {% for line in pedido.itempedido_set.all %}
                    <tr>
                        <th class="d-none d-lg-block">Imagem</th>
                        <th>Produto</th>
                        <th>V.</th>
                        <th>QTD.</th>
                        <th>Total</th>
                    </tr>


                    <tr>
                        <td class="d-none d-lg-block">
                            <img class="cart-img" src="{% get_media_prefix %}{{line.image}}">
                        </td>
                        <td>{{line.product}}</td>
                        <td>{{line.variation}}</td>
                        <td>{{line.quantity}}</td>
                        {% if line.promotional_price %}
                            <td>{{line.promotional_price|format_money}}</td>
                        {% else %}
                            <td>{{line.price|format_money}}</td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </table>
        </div>


        
        
    </div>
</div>

templates/partials/_scripts.html
{% load static %}
<script src="{% static 'assets/bootstrap/js/jquery-3.2.1.slim.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/popper.min.js' %}"></script>
<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
<script defer src="{% static 'assets/font-awesome/js/all.js' %}"></script>
<script src="{% static 'assets/custom/js/scripts.js' %}"></script>