order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>/', views.Payment.as_view(), name='pay'),
    path('save-order/', views.SaveOrder.as_view(), name='save_order'),
    path('list-order/', views.ListOrder.as_view(), name='list_order'),
    path('order-detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
"""
Pedido:
        user - FK User
        total - Float
        status - Choices
            ('A', 'Aprovado'),
            ('C', 'Criado'),
            ('R', 'Reprovado'),
            ('P', 'Pendente'),
            ('E', 'Enviado'),
            ('F', 'Finalizado'),

        ItemPedido:
            pedido - FK pedido
            produto - Char
            produto_id - Int
            variacao - Char
            variacao_id - Int
            preco - Float
            preco_promocional - Float
            quantidade - Int
            imagem - Char
"""
STATUS_CHOICES = (
    ('A', 'Aprovado'), ('P', 'Pendente'), ('C', 'Criado'), 
    ('R', 'Recusado'), ('E', 'Enviado'), ('F', 'Finalizado'),
)


class Pedido(models.Model):
    user = models.ForeignKey(User, models.DO_NOTHING, verbose_name='Usuário')
    total = models.FloatField()
    total_quantity = models.PositiveIntegerField()
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='C')
    
    def __str__(self):
        return f'Pedido Nº {self.pk}'


class ItemPedido(models.Model):
    order = models.ForeignKey(Pedido, models.CASCADE, verbose_name='Pedido')
    product = models.CharField('Produto', max_length=255)
    product_id = models.PositiveIntegerField('ID do produto')
    variation = models.CharField('Variação', max_length=100)
    variation_id = models.PositiveIntegerField('ID da variação')
    price = models.FloatField(verbose_name='Preço')
    promotional_price = models.FloatField('Preço promocional')
    quantity = models.PositiveIntegerField('Quantidade')
    image = models.CharField(max_length=2000, verbose_name='Imagem')

    def __str__(self):
        return f'Item do {self.order}'.capitalize()
    
    class Meta:
        verbose_name = 'Item do pedido'
        verbose_name_plural = 'Itens do pedido'

order/views.py
from django.shortcuts import render, redirect
from utils import functions
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib import messages

from product.models import Variacao
from django.contrib.auth.mixins import LoginRequiredMixin
from . import models


class LoginRequiredBaseMixin(LoginRequiredMixin, View):
    login_url = 'perfil:create'
    permission_denied_message = 'Você não tem permissão para acessar esta pagina'
    
    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(user=self.request.user)
        return qs 


class Payment(LoginRequiredBaseMixin, DetailView):
    template_name = 'topay.html'
    model = models.Pedido
    pk_url_kwarg = 'pk'


class SaveOrder(Payment):
    template_name = 'topay.html'
    
    def get(self, *args, **kwargs):
        context = {}
        render_ = render(self.request, self.template_name, context)
        if not self.request.user.is_authenticated:
            return redirect('perfil:create')
        
        if not self.request.session.get('carrinho'):
            messages.error(self.request, 'Carrinho vazio.')
            return render_
        
        cart = self.request.session.get('carrinho')
        products_vars = list(cart.keys())
        db_var = list(Variacao.objects.filter(id__in=products_vars))
        
        enough = True
        for var in db_var:
            vid = str(var.id)
            stock = var.stock
            cart_quantity = cart[vid]['quantity']
            unt_price = cart[vid]['unit_price']
            promotional_unit_price = cart[vid]['promotional_unit_price']

            if stock < cart_quantity:
                cart[vid]['quantity'] = stock
                cart[vid]['quantitative_price'] = stock * unt_price
                cart[vid]['promotional_quantitative_price'] = stock * promotional_unit_price
                enough = False
        
        if not enough:
            messages.warning(
                self.request, 'Alguns itens foram reduzidos por estoque insuficiente.'
                              'verifique os itens abaixo antes de continuar.'
            )
            
            self.request.session.save()
            return redirect(self.request.META.get('http_referer', 
                                                  'product:purchase_summary'))
        
        cart_total_quantity = functions.get_cart_quantity(cart)
        cart_total_value = functions.amount(cart)
        
        order = models.Pedido(
            user=self.request.user, 
            total=cart_total_value, 
            total_quantity=cart_total_quantity,
            status='C'
        )
        order.save()
        
        models.ItemPedido.objects.bulk_create(
                [models.ItemPedido(
                    order = order,
                    product = v['product_name'],
                    product_id = v['product_id'],
                    variation = v['variation_name'],
                    variation_id = v['variation_id'],
                    price = v['quantitative_price'],
                    promotional_price = v['promotional_quantitative_price'],
                    quantity = v['quantity'],
                    image = v['image'],
                ) for v in cart.values()]
            )
        del self.request.session['carrinho']
        return redirect('order:pay', pk=order.pk)

class Detail(LoginRequiredBaseMixin, DetailView):
    login_url = 'perfil:create'
    model = models.Pedido
    template_name = 'detail.html'
    ordering = ['-id']


class ListOrder(LoginRequiredBaseMixin, ListView):
    login_url = 'perfil:create'
    model = models.Pedido
    context_object_name = 'orders'
    template_name = 'list_orders.html'
    paginate_by = 10
    ordering = ['-id']

order/templates/detail.html
{% extends 'base.html' %}

{% block title %}{{pedido}}{% endblock title %}

{% block content %}

{% include 'partials/_products.html' %}

{% endblock content %}

order/templates/list_orders.html
{% extends 'base.html' %}
{% load myfilters %}

{% block title %}Meus pedidos{% endblock title %}

{% block content %}

<div class="row">
    <div class="col">
        <h3 class="mb-4">Pedidos de {{user}}</h3>
        <p>Abaixo todos os seus pedidos realizados na loja.</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <tr>
                    <th scope="col">Pedido</th>
                    <th scope="col">Total</th>
                    <th scope="col">Qtd. Itens</th>
                    <th scope="col">Status</th>
                    <th scope="col">Mais detalhes</th>
                </tr>

                {% for order in orders %}
                    <tr>
                        <th scope="row">{{order}}</td>
                        <td>{{order.total|format_money}}</td>
                        <td>{{order.total_quantity}}</td>
                        <td>{{order.get_status_display}}</td>
                        <td>
                            <a href="{% url 'order:detail' order.pk %}">
                                Ver <i class="fas fa-search-plus ml-2"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% include 'partials/_pagination.html' %}

{% endblock content %}

order/templates/topay.html
{% extends 'base.html' %}
{% load static %}
{% load myfilters %}

{% block title %}Realizar pagamento{% endblock title %}

{% block content %}
<div class="row">
    <div class="col">
        <h3>Escolha o método de pagamento</h3>
        <p>Para o desenvolvedor: adicione seu método de pagamento preferido.</p>
    </div>
</div>

{% include 'partials/_products.html' %}

<div class="row mt-4">
    <div class="col">
        <a href="#" class="btn btn-primary btn-block btn-lg">Pagar</a>
    </div>
</div>
{% endblock content %}