order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('pay/<int:pk>/', views.Payment.as_view(), name='pay'),
    path('save-order/', views.SaveOrder.as_view(), name='save_order'),
    path('list-order/', views.ListOrder.as_view(), name='list_order'),
    path('order-detail/<int:pk>', views.Detail.as_view(), name='detail'),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = 'perfil'

urlpatterns = [
    path('', views.CreatePerfil.as_view(), name='create'),
    path('update/', views.UpdatePerfil.as_view(), name='update'),
    path('login/', views.LoginPerfil.as_view(), name='login'),
    path('logout/', views.LogoutPerfil.as_view(), name='logout'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'


urlpatterns = [
    path('', views.ListProduct.as_view(), name='list_products'),
    path('add-to-cart/', views.AddToCart.as_view(), name='add_to_cart'),
    path('remove-to-cart/', views.RemoveToCart.as_view(), name='remove_to_cart'),
    path('cart/', views.Cart.as_view(), name='cart'),
    path('purchase-summary/', views.PurchaseSummary.as_view(), name='purchase_summary'),
    path('search/', views.SearchProduct.as_view(), name='search_product'),
    path('<str:slug>/', views.ProductDetail.as_view(), name='details'),
]

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('order/', include('order.urls')),
    path('perfil/', include('perfil.urls')),
    path('', include('product.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

product/models.py
from django.db import models
from PIL import Image
from django.utils.text import slugify
from utils import functions

CHOICES = ('V', 'Variável'), ('S', 'Simples')
IMG_DEFAULT_SIZE = (400, 250)


class Produto(models.Model):
    name = models.CharField('Nome', max_length=255)
    short_description = models.TextField(
        'Descrição curta', blank=True, null=True, max_length=200
    )
    long_description = models.TextField('Descrição longa', blank=True, null=True)
    image = models.ImageField('Imagem do produto', upload_to='products/img/%Y/%b/')
    slug = models.SlugField('Slug', unique=True, blank=True, null=True)
    marketing_price = models.FloatField('Preço marketing')
    promotional_marketing_price = models.FloatField(
        'Preço marketing promocional', default=0
    )
    variation_type = models.CharField(
        'Tipo', max_length=1, choices=CHOICES, default='V'
    )
    
    def __str__(self) -> str:
        return self.name
    
    def save(self, *args, **kwargs) -> None:
        if not self.slug:
            try:
                pk = Produto.objects.all().order_by('-id').first().id + 1
            except:
                pk = 1
            self.slug = f'{slugify(self.name)}-{pk}'
            
        super().save(*args, **kwargs)
        self.resize_image()

    def resize_image(self):        
        img = Image.open(self.image.path)
        x, y = img.size
        if x <= IMG_DEFAULT_SIZE[0] and y <= IMG_DEFAULT_SIZE[1]:
            img.close()
            return
        
        new_img = img.resize(IMG_DEFAULT_SIZE, Image.ANTIALIAS)
        new_img.save(self.image.path, quality=70, optimize=True)
        img.close()
        new_img.close()
    
    def get_marketing_price_formatted(self):
        return functions.format_money_value(self.marketing_price)
    get_marketing_price_formatted.short_description = 'Preço'
    
    def get_promotional_price_formatted(self):
        return functions.format_money_value(self.promotional_marketing_price)
    get_promotional_price_formatted.short_description = 'Preço promocional'

 
class Variacao(models.Model):
    product = models.ForeignKey(Produto, models.CASCADE, verbose_name='Produto')
    name = models.CharField(
        'Nome', max_length=255, default=product.name
    )
    price = models.FloatField('Preço')
    promotional_price = models.FloatField('Preço promocional', default=0)
    stock = models.PositiveIntegerField('Estoque', default=1)
    
    def __str__(self):
        return self.name or self.product.name
    
    
    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Variações'
        

product/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from perfil.models import Perfil
from django.contrib import messages
from .models import Produto, Variacao
from django.db.models import Q


class ListProduct(ListView):
    model = Produto
    template_name = 'list.html'
    context_object_name = 'products'
    paginate_by = 10
    ordering = ['-id']


class ProductDetail(DetailView):
    model = Produto
    template_name = 'details.html'
    context_object_name = 'product_detail'
    slug_url_kwarg = 'slug'

class AddToCart(View):
    def get(self, *args, **kwargs):            
        http_referer = self.request.META.get('HTTP_REFERER', reverse('product:list_products'))
        variation_id = self.request.GET.get('vid')
        if not variation_id:
            messages.error(self.request, 'Error')
            return redirect(http_referer)
        
        variation = get_object_or_404(Variacao, id=variation_id)
        product = variation.product
        unit_price = variation.price
        promotional_unit_price = variation.promotional_price
        
        if variation.stock < 1:
            messages.error(self.request, 'Estoque insuficiente.')
            return redirect(http_referer)
        
        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()
            
        was_add = True
        carrinho = self.request.session['carrinho']            
        if variation_id in carrinho:
            stock = variation.stock
            cart_quantity = carrinho[variation_id]['quantity']
            cart_quantity += 1
            if stock < cart_quantity:
                messages.warning(self.request, 'Estoque insuficiente.')
                cart_quantity = variation.stock
                was_add = False
                
            carrinho[variation_id]['quantity'] = cart_quantity
            carrinho[variation_id]['quantitative_price'] = cart_quantity * unit_price
            carrinho[variation_id]['promotional_quantitative_price'] = cart_quantity * promotional_unit_price
            
        
        else:
            carrinho[variation_id] = dict(
                product_id = product.id,
                product_name = product.name,
                variation_name = variation.name,
                variation_id = variation.id,
                unit_price = unit_price,
                promotional_unit_price = promotional_unit_price,
                quantity = 1,
                slug = product.slug,
                image = product.image.name if product.image else '',
                
            )
            quantity = carrinho[variation_id]['quantity']
            carrinho[variation_id]['quantitative_price'] = quantity * unit_price
            carrinho[variation_id]['promotional_quantitative_price'] = quantity * promotional_unit_price
        
        self.request.session.save()
        if was_add:
            messages.success(self.request, f'{product.name} adicionado ao carrinho.')
        return redirect(http_referer)


class RemoveToCart(View):
    def get(self, request, *args, **kwargs):
        http_referer = self.request.META.get('HTTP_REFERER', reverse('product:list_products'))
        variation_id = self.request.GET.get('vid')
        carrinho = self.request.session.get('carrinho')
        if not variation_id:
            return redirect(http_referer)
        
        if not variation_id or not carrinho or variation_id not in carrinho:        
            return redirect(http_referer)

        product_name = carrinho[variation_id]['product_name']
        variation_name = carrinho[variation_id]['variation_name']
        messages.warning(
            self.request, 
            f'{product_name} {variation_name} removido.'
        )
        del self.request.session['carrinho'][variation_id]
        self.request.session.save()
        return redirect(http_referer)


class Cart(View):
    def get(self, request, *args, **kwargs):
        return render(self.request, 'cart.html')


class PurchaseSummary(View):
    def get(self, request, *args, **kwargs):
        if not self.request.user.is_authenticated:
            return redirect('perfil:create')
        
        perfil = Perfil.objects.filter(user=self.request.user).exists()
        if not perfil:
            messages.error(self.request, 'Usuário não tem perfil.')
            return redirect('perfil:create')
        
        if not self.request.session.get('carrinho', {}):
            messages.error(self.request, 'Carrinho vazio.')
            return redirect('product:list_products')
        
        context = {
            'user': self.request.user,
            'cart': self.request.session.get('carrinho', {})
        }
        return render(self.request, 'salesummary.html', context)


class SearchProduct(ListProduct):
    def get_queryset(self, *args, **kwargs):
        search_field = self.request.GET.get('search_field') or self.request.session.get('search_fiedl')
        qs = super().get_queryset(*args, **kwargs)
        if not search_field: return qs
        
        self.request.session['search_fiedl'] = search_field
        
        qs = qs.filter(
            Q(name__icontains=search_field)|
            Q(short_description__icontains=search_field)|
            Q(long_description__icontains=search_field)
        )
        
        self.request.session.save()
        return qs
    

product/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% load myfilters %}

{% block title %}Carrinho{% endblock title %}

{% block content %}
{% if request.session.carrinho %}

<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        {% include 'partials/_cart.html' %}

    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>R${{request.session.carrinho|total_cart|format_money}}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        {% if request.user.is_authenticated %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'product:purchase_summary' %}">
                continuar
            </a>
        {% else %}
            <a class="btn btn-lg btn-block btn-primary" href="{% url 'perfil:create' %}">
                continuar
            </a>
        {% endif %}
    </div>
</div>

{% else %}
    <p>O seu carrinho está vazio.</p>
{% endif %}
{% endblock content %}

product/templates/details.html
{% extends 'base.html' %}
{% load myfilters %}

{% block title %}
{{product_detail.name}}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">

                        {% if product_detail.image %}
                            <img class="img-fluid" src="{{product_detail.image.url}}">
                        {% endif %}

                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{product_detail.name}}</h1>
                    <p class="lead">{{product_detail.short_description|linebreaks}}</p>
                    
                    <p class="lead">

                        {% if product_detail.promotional_marketing_price %}
                            <span id="variation-preco-promocional" class="lead product-price">
                                {{product_detail.promotional_marketing_price|format_money}}
                            </span>
                            <span id="variation-preco"
                                class="lead product-old-price text-muted">
                                {{product_detail.marketing_price|format_money}}
                            </span>
                        {% else %}
                            <span id="variation-preco"
                            class="lead product-price">{{product_detail.marketing_price|format_money}}</span>
                        {% endif %}
                    </p>

                    <form action="{% url 'product:add_to_cart' %}" id="form-add-to-cart">
                        <div class="form-group">
                            
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">

                                    {% for variation in product_detail.variacao_set.all %}
                                        {% if variation.promotional_price %}
                                        
                                            <option data-preco="{{variation.price|format_money}}" 
                                            data-preco-promocional="{{variation.promotional_price|format_money}}" 
                                            value="{{variation.id}}">
                                                {{variation.name}}
                                            </option>

                                        {% else %}

                                            <option data-preco="{{variation.promotional_price|format_money}}" 
                                            data-preco-promocional="{{variation.price|format_money}}" 
                                            value="{{variation.id}}">
                                                {{variation}}
                                            </option>

                                        {% endif %}

                                    {% endfor %}
                                    
                                </select>

                        </div>

                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>
                    </form>


                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">Descrição</h2>
                    <hr>
                    <p>{{product_detail.long_description|linebreaksbr}}</p>

                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

product/templates/list.html
{% extends 'base.html' %}
{% load myfilters %}


{% block content %}
<div class="row">
    <div class="col-lg-12">
        <div class="card-columns">

            {% for product in products %}
            <div class="card">

                {% if product.image %}
                    <a href="{% url 'product:details' product.slug %}">
                    <img class="card-img-top" src="{{product.image.url}}" alt="{{product.image.name}}">
                    </a>
                {% endif %}
                
                <div class="card-body">
                    <h5 class="card-title">{{product.name}}</h5>
                    <p class="card-text">{{product.short_description}}</p>

                    <div class="container product-price-block text-center">
                        {% if product.promotional_marketing_price %}
                            <span class="product-price">
                                {{product.promotional_marketing_price|format_money}}
                            </span>
                            <span class="product-old-price text-muted">
                                {{product.marketing_price|format_money}}
                            </span>
                        {% else %}
                                <span class="product-price">
                                    {{product.marketing_price|format_money}}
                                </span>
                        {% endif %}
                    </div>
                </div>
                <div class="card-footer bg-transparent border-top-light-custom text-center">
                    <a href="{% url 'product:details' product.slug %}" class="btn btn-primary btn-sm m-1 btn-block">
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                        Comprar
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<div class="row">
    <div class="col mt-3">
        {% include 'partials/_pagination.html' %}
    </div>
</div>

{% endblock content %}

product/templates/salesummary.html
{% extends 'base.html' %}
{% load myfilters %}

{% block title %}Resumo da compra{% endblock title %}

{% block content %}
<div class="row mb-5">
    <div class="col-lg">
        <h2>Resumo da sua compra</h2>

        <p class="lead">Dados do usuário</p>

        <dl class="row">
            <dt class="col-lg-2">Nome:</dt>
            <dd class="col-lg-4">{{user.first_name}}</dd>
            <dt class="col-lg-2">Sobrenome:</dt>
            <dd class="col-lg-4">{{user.last_name}}</dd>

            <dt class="col-lg-2">Idade:</dt>
            <dd class="col-lg-4">{{user.perfil.birthday|calculate_age}}</dd>
            <dt class="col-lg-2">Nascimento:</dt>
            <dd class="col-lg-4">{{user.perfil.birthday}}</dd>

            <dt class="col-lg-2">CPF:</dt>
            <dd class="col-lg-4">{{user.perfil.cpf}}</dd>
            <dt class="col-lg-2">E-mail:</dt>
            <dd class="col-lg-4">{{user.email}}</dd>
        </dl>

        <p class="lead">Dados de endereço</p>
        
        <dl class="row">
            <dt class="col-lg-2">Endereço:</dt>
            <dd class="col-lg-4">{{user.perfil.address}}</dd>
            <dt class="col-lg-2">Número:</dt>
            <dd class="col-lg-4">{{user.perfil.number}}</dd>

            <dt class="col-lg-2">Complemento:</dt>
            <dd class="col-lg-4">{{user.perfil.complement}}</dd>
            <dt class="col-lg-2">Bairro:</dt>
            <dd class="col-lg-4">{{user.perfil.neighborhood}}</dd>

            <dt class="col-lg-2">Cidade:</dt>
            <dd class="col-lg-4">{{user.perfil.city}}</dd>
            <dt class="col-lg-2">Estado:</dt>
            <dd class="col-lg-4">{{user.perfil.state}}</dd>

            <dt class="col-lg-2">CEP:</dt>
            <dd class="col-lg-4">{{user.perfil.cep}}</dd>
        </dl>
        <p><a href="{% url 'perfil:create' %}">Editar dados</a></p>
    </div>
</div>



<div class="row">
    {% include 'partials/_cart.html' %}
</div>

<div class="row">
    <div class="col">
        <p class="lead text-center">
            <span class="font-weight-bold">Total:</span> {{cart|total_cart|format_money}}
        </p>
        <a class="btn btn-block btn-primary btn-lg" href="{% url 'order:save_order' %}">
            Realizar pedido e pagar
        </a>
    </div>
</div>
{% endblock content %}